### ISSUE TITLE
Inverse default hoogfile creation behavior

### ISSUE THREAD

**Issue by anmuel** [GateprotectGmbH/captain_hoog#15]
At the moment the captain tries to create a new hoogfile each time the user does `hoog install`.
This forces the user to select "n" each time - if you want to have 4 hoogs in your repository, you have to type "n" 4 times.
From my point of view this is annoying and thus I suggest to change the behavior.

Only create a new hoogfile if the install command gets called with a --create (or something) option and otherwise only create the hook within .git

**Comment by dsci** [comment]
It would suggest kind of strange behaviour - user has to install the captain and additional has to say let's create the hoogfile for me. I would suggest the other way around to have a --skip-hoogfile flag or an update command.

**Comment by anmuel** [comment]
Fine with that.
